name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  update-manifest:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update image tag in deployment.yaml
        run: |
          sed -i "s|image: netflix.azurecr.io/netflix:.*|image: netflix.azurecr.io/netflix:${{ github.run_id }}|g" Kubernetes/deployment.yml

      - name: Commit and push changes
        run: |
          git config --global user.email "ishwaryadevopsen@gmail.com"
          git config --global user.name "Sharnitha"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${{ github.run_id }}"
          git push
